### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tianyilt** [tianyilt/ECNU-CourseShare#1]
计划：

- [x] 先参考https://github1s.com/tianyilt/ecust-CourseShare 初始化几个课程
- [ ] 把logo补上
- [ ] 找队友
- [x] 在你们和JJAYCHEN 和Bill Chen的帮助下把CS和软工的给初始化
- [ ] 确定本科生的项目owner，因为我是研究生，忙着维护PGCourse还有科研工作
